import { Brain, Scan, Activity, ArrowRight, Utensils, MessagesSquare, Dumbbell } from "lucide-react";
import AiFeature from "../../assets/AiFeature.png";
import { useScrollAnimation } from "../../hooks/useScrollAnimation";
import { Link } from "react-router-dom";

function AiFeatures() {
  const { ref: sectionRef, isVisible } = useScrollAnimation({ threshold: 0.15 });

  return (
    <section ref={sectionRef} className="w-full bg-gradient-to-r from-amber-50/40 via-background to-orange-50/40 py-24">
      <div className={`mx-auto flex w-full max-w-7xl px-4 sm:px-6 flex-col overflow-hidden rounded-[32px] border border-amber-100 bg-white/50 backdrop-blur-sm shadow-xl lg:flex-row transition-all duration-700 ease-out hover:shadow-2xl hover:border-amber-200 ${isVisible ? "translate-y-0 opacity-100" : "translate-y-8 opacity-0"
        }`}>

        {/* Content Side */}
        <div className={`flex flex-1 flex-col justify-center gap-10 px-6 py-12 transition-all duration-700 ease-out sm:px-10 lg:px-12 ${isVisible ? "translate-x-0 opacity-100" : "-translate-x-8 opacity-0"
          }`}>
          <header className="space-y-4">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#FF8211]/10 text-[#FF8211] w-fit">
              <Brain className="w-4 h-4" />
              <p className="text-xs font-bold uppercase tracking-wider">
                Artificial Intelligence
              </p>
            </div>
            <h3 className="font-bebas text-4xl tracking-tight text-gray-900 sm:text-5xl leading-[0.9]">
              Future of Fitness <br />
              <span className="text-[#FF8211]">Powered by AI</span>
            </h3>
            <p className="text-base text-gray-500 sm:text-lg leading-relaxed max-w-lg">
              Unlock your full potential with our suite of AI-powered tools designed to optimize every aspect of your fitness journey.
            </p>
          </header>

          <div className="space-y-8">
            <Link to="/ai-food" className="flex gap-5 group items-start hover:bg-white/60 p-4 -ml-4 rounded-2xl transition-all">
              <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-[#FF8211]/10 text-[#FF8211] group-hover:bg-[#FF8211] group-hover:text-white transition-colors duration-300">
                <Utensils className="h-6 w-6" />
              </div>
              <div>
                <dt className="text-lg font-bold text-gray-900 mb-1 flex items-center gap-2">
                  AI Food Analyzer
                  <span className="text-[#FF8211] opacity-0 group-hover:opacity-100 transition-opacity">→</span>
                </dt>
                <dd className="text-sm text-gray-500 leading-relaxed">
                  Snap a photo of your meal and get instant caloric and macronutrient breakdowns. Optimizing your diet has never been this easy.
                </dd>
              </div>
            </Link>

            <Link to="/ai-trainer" className="flex gap-5 group items-start hover:bg-white/60 p-4 -ml-4 rounded-2xl transition-all">
              <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-[#FF8211]/10 text-[#FF8211] group-hover:bg-[#FF8211] group-hover:text-white transition-colors duration-300">
                <Dumbbell className="h-6 w-6" />
              </div>
              <div>
                <dt className="text-lg font-bold text-gray-900 mb-1 flex items-center gap-2">
                  AI Personal Trainer
                  <span className="text-[#FF8211] opacity-0 group-hover:opacity-100 transition-opacity">→</span>
                </dt>
                <dd className="text-sm text-gray-500 leading-relaxed">
                  Get personalized workout plans, form corrections, and adaptive training schedules generated by our advanced AI trainer.
                </dd>
              </div>
            </Link>

            <Link to="/ai-chat" className="flex gap-5 group items-start hover:bg-white/60 p-4 -ml-4 rounded-2xl transition-all">
              <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-[#FF8211]/10 text-[#FF8211] group-hover:bg-[#FF8211] group-hover:text-white transition-colors duration-300">
                <MessagesSquare className="h-6 w-6" />
              </div>
              <div>
                <dt className="text-lg font-bold text-gray-900 mb-1 flex items-center gap-2">
                  AI Chat Assistant
                  <span className="text-[#FF8211] opacity-0 group-hover:opacity-100 transition-opacity">→</span>
                </dt>
                <dd className="text-sm text-gray-500 leading-relaxed">
                  Have questions about fitness or nutrition? Chat with our intelligent assistant 24/7 for instant answers and guidance.
                </dd>
              </div>
            </Link>
          </div>

        </div>

        {/* Image Side */}
        <div className={`relative min-h-[400px] w-full flex-1 lg:h-auto overflow-hidden ${isVisible ? "translate-x-0 opacity-100" : "translate-x-8 opacity-0"
          } transition-all duration-700 delay-300 ease-out`}>
          <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent z-10" />
          <img
            src={AiFeature}
            alt="AI Fitness Technology"
            className="h-full w-full object-cover transition-transform duration-700 hover:scale-105"
          />
        </div>
      </div>
    </section>
  );
}

export default AiFeatures;
